config/routes.rb
Rails.application.routes.draw do
  resources :documents

  resources :sessions, only: [:new, :create] do
    delete 'logout', on: :collection
  end
  root to: 'documents#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user

  def user_name
    user ? user.name : ''
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :documents

  def self.find_version_author(version)
    find(version.terminator)   
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end

  def require_user
    redirect_to new_session_path unless current_user
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_user
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.user_id = current_user.id

    if @document.save
      redirect_to edit_document_path(@document), notice: "New document saved."
    else
      render :new
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    if @document.update(document_params)
      redirect_to edit_document_path(@document), notice: "Document updated."
    else
      render :edit
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :content, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.where(name: params[:name]).first_or_create
    session[:user_id] = user.id
    redirect_to documents_path
  end

  def logout
    session[:user_id] = nil
    redirect_to documents_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document, { role: 'form' }) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control document-text-area' %>
  </div>
  <div class='fr'>
    <%= link_to 'Back', documents_path, class: 'btn btn-danger' %>
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.user_name %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PapertrailTuto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'PaperTrail - Jutsu #8', root_path, class: 'navbar-brand' %>
      </div>
      <%- if current_user %>
        <div class='navbar-text'>
          Logged in as <%= current_user.name %>
          |
          <%= link_to 'Logout', logout_sessions_path, method: 'delete' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%- if notice %><p class="notice bg-success"><%= notice %></p><% end %>
    <%- if alert %><p class="notice bg-danger"><%= alert %></p><% end %>
    <%= yield %>
  </div>
      
</body>
</html>